name: gatby-preview-lanceMcCarthy

on:
  workflow_dispatch: {}
 
jobs:

  BuildDeploy:
    env:
      CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      CONTENTFUL_PREVIEW_KEY: ${{ secrets.CONTENTFUL_PREVIEW_KEY }}
      CONTENTFUL_PREVIEW_HOST: ${{ secrets.CONTENTFUL_PREVIEW_HOST }}
      AZURE_STORAGE_ACCOUNT_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_ACCOUNT_CONNECTION_STRING }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Using cached node_modules
        uses: actions/cache@v2
        with:
         path: "**/node_modules"
         key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Using cached .cache
        uses: actions/cache@v2
        with:
         path: ".cache"
         key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Using cached public
        uses: actions/cache@v2
        with:
         path: "public"
         key: ${{ runner.os }}-public-${{ hashFiles('**/package-lock.json') }}

      - name: Restore Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload to Blob Storage  
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        with:
          connection_string: ${{ env.AZURE_STORAGE_ACCOUNT_CONNECTION_STRING }}
          container_name: gatsby-preview
          source_folder: public